---

- name: Install python for Ansible
  become: yes
  become_user: root
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  changed_when: False
  tags: 
    - pre-configure
    - configure 
    - deploy-all
