---

- name: Preconfiguration of the instance
  hosts: server_ip
  become: True
  gather_facts: False
  roles:
    - role: pre_configure

- name: Deploy Moodle to the server
  hosts: server_ip
  become: True
  gather_facts: True
  roles:
    - role: configure
    - role: moodle_run
